### ISSUE TITLE
Core dumped in ambient_occlusion computation

### ISSUE THREAD

**Issue by samiarshad** [mmspg/mesh-sampling#1]
Hi,

Thanks for sharing the script.

I have been trying to sample points from the chair subset of ShapeNet dataset. However, while running the color sampling script, the program exits around 'ms.ambient_occlusion' with the error message 'Aborted (core dumped)'.

Any idea why this is happening?

System- 
OS: Ubuntu 20.04
pymeshlab==2021.10

Thanks

**Comment by jtawade** [comment]
Were you able to find a solution to this problem? I'm currently running into the same issue

**Comment by CuiRuikai** [comment]
same problem, solved by 

`pip install pymeshlab==2021.10`
